import type { Metadata } from "next";
import { Providers } from "@/providers/heroui-provider";
import "./globals.css";

export const metadata: Metadata = {
	title: "Hono | nextjs",
	description: "Generated by hono",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
